#TYPE CHANGE IF IT IS POSSIBLE
x=input("please enter the string= ")
print(type(x))
i=str(x)
print(type(i))
print("TYPE IS CHANGED")
y=input("please enter int no = ")
print(type(y))
j=int(y)
print(type(j))
print("TYPE IS CHANGED")
z=input("please enter float no = ")
print(type(z))
k=float(z)

print(type(k))
print("TYPE IS CHANGED")
a=input("please enter bool = ")
print(type(a))
l=bool(a)

print(type(l))
print("TYPE IS CHANGED")
b=input("please enter list = ")
print(type(b))
m=list(b)
print(type(m))
print("TYPE IS CHANGED")
